name = "wimp"
version = "1.0.0"
description = "A Gleam client for the Pushover push notification API"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "wimp-pushover" }
links = [
  { title = "Website", href = "https://pushover.net/" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_json = "~> 0.6"
gleam_http = "~> 3.5"

[dev-dependencies]
gleeunit = "~> 0.10"
gleam_httpc = "~> 2.1"
